export const componentGroups = [
  {
    name: "作業面と移動",
    ids: [
      "app-shell",
      "command-menu",
      "split-view",
      "wing",
      "section",
      "surface",
      "context-bar",
      "page-header",
      "profile-header",
      "breadcrumb",
      "back-link",
      "navigation",
      "tree",
      "table-of-contents",
      "tabs",
      "pagination",
      "steps",
      "divider",
    ],
  },
  {
    name: "入力と選択",
    ids: [
      "field",
      "field-group",
      "optional-fields",
      "input-group",
      "copy-field",
      "switch",
      "toggle-group",
      "range",
      "dial",
      "suggestion",
      "picker",
      "emoji-picker",
      "inline-select",
      "color-picker",
      "tag-input",
      "date-picker",
      "date-time-range",
      "file-input",
      "image-cropper",
      "composer",
      "text-editor",
      "filter-bar",
    ],
  },
  {
    name: "操作と補足",
    ids: [
      "button",
      "split-button",
      "action-tile",
      "toolbar",
      "action-dock",
      "dropdown-menu",
      "filter-menu",
      "dialog",
      "popover",
      "tooltip",
      "hover-card",
      "disclosure",
      "danger-zone",
      "keycap",
    ],
  },
  {
    name: "内容と一覧",
    ids: [
      "card",
      "layer-card",
      "message",
      "message-list",
      "search-results",
      "table",
      "grid",
      "treegrid",
      "value-list",
      "setting-list",
      "editable-property",
      "data-list",
      "action-list",
      "file-item",
      "image-frame",
      "carousel",
      "comparison",
      "chart-frame",
      "avatar",
      "tag",
      "reactions",
      "icon",
      "code-block",
    ],
  },
  {
    name: "仕事と予定",
    ids: ["task-list", "timeline", "calendar", "board", "statistic", "countdown"],
  },
  {
    name: "状態と結果",
    ids: [
      "badge",
      "notice",
      "prompt",
      "error-summary",
      "empty-state",
      "progress",
      "loading",
      "toast",
    ],
  },
] as const;
